"use client";

import {
  User, Package, Ticket, Bot, Crosshair, Settings, BarChart3,
  Users, Info, Lock, Download, Dices, ClipboardList, Key,
  Trash2, Pencil, X, Menu, ArrowLeft, LogOut, FileText,
  Heart, Clover, Ruler, Home, Wand, Search, Plus, Zap, Skull, Image,
  ImagePlus, Smile, MessageSquareLock, EyeOff, Loader2, Send, Minus, ChevronDown, ChevronLeft, ChevronRight,
  Copy, SlidersHorizontal, Navigation, MessageSquare, Check, CheckCheck,
  Target, Eye, Droplet, Braces, Clock,
  HelpCircle, AlertTriangle, UserPlus, CheckSquare,
  RefreshCw, Share2, Box, File, Stamp,
  ArrowDown, ArrowUp, ChevronsUp, ChevronsDown, Ban, Sparkles, ScrollText, Flag,
  Sunrise, Sun, Moon, CalendarDays, Undo2,
  NotebookPen, BookOpen, AtSign, Bold, Italic, Heading2, List, Quote, Link2, MoreVertical,
  type LucideIcon,
} from "lucide-react";

interface IconProps {
  className?: string;
}

const wrap = (Icon: LucideIcon) => {
  const Component = ({ className }: IconProps) => <Icon className={className || "w-5 h-5"} />;
  Component.displayName = Icon.displayName || Icon.name;
  return Component;
};

export const Icons = {
  User: wrap(User),
  Package: wrap(Package),
  Ticket: wrap(Ticket),
  Bot: wrap(Bot),
  Crosshair: wrap(Crosshair),
  Settings: wrap(Settings),
  BarChart3: wrap(BarChart3),
  Users: wrap(Users),
  Info: wrap(Info),
  Lock: wrap(Lock),
  Download: wrap(Download),
  Dices: wrap(Dices),
  ClipboardList: wrap(ClipboardList),
  Key: wrap(Key),
  Trash2: wrap(Trash2),
  Pencil: wrap(Pencil),
  X: wrap(X),
  Menu: wrap(Menu),
  ArrowLeft: wrap(ArrowLeft),
  LogOut: wrap(LogOut),
  FileText: wrap(FileText),
  Heart: wrap(Heart),
  Clover: wrap(Clover),
  Ruler: wrap(Ruler),
  Home: wrap(Home),
  Wand: wrap(Wand),
  Search: wrap(Search),
  Plus: wrap(Plus),
  Zap: wrap(Zap),
  Skull: wrap(Skull),
  Image: wrap(Image),
  ImagePlus: wrap(ImagePlus),
  Smile: wrap(Smile),
  MessageSquareLock: wrap(MessageSquareLock),
  EyeOff: wrap(EyeOff),
  Loader2: wrap(Loader2),
  Send: wrap(Send),
  Minus: wrap(Minus),
  ChevronDown: wrap(ChevronDown),
  ChevronLeft: wrap(ChevronLeft),
  ChevronRight: wrap(ChevronRight),
  Copy: wrap(Copy),
  SlidersHorizontal: wrap(SlidersHorizontal),
  Navigation: wrap(Navigation),
  MessageSquare: wrap(MessageSquare),
  Check: wrap(Check),
  CheckCheck: wrap(CheckCheck),
  Target: wrap(Target),
  Eye: wrap(Eye),
  Droplet: wrap(Droplet),
  Braces: wrap(Braces),
  Clock: wrap(Clock),
  HelpCircle: wrap(HelpCircle),
  AlertTriangle: wrap(AlertTriangle),
  UserPlus: wrap(UserPlus),
  CheckSquare: wrap(CheckSquare),
  RefreshCw: wrap(RefreshCw),
  Share2: wrap(Share2),
  Box: wrap(Box),
  File: wrap(File),
  Stamp: wrap(Stamp),
  ArrowDown: wrap(ArrowDown),
  Ban: wrap(Ban),
  Sparkles: wrap(Sparkles),
  Sunrise: wrap(Sunrise),
  Sun: wrap(Sun),
  Moon: wrap(Moon),
  CalendarDays: wrap(CalendarDays),
  Undo2: wrap(Undo2),
  NotebookPen: wrap(NotebookPen),
  BookOpen: wrap(BookOpen),
  AtSign: wrap(AtSign),
  Bold: wrap(Bold),
  Italic: wrap(Italic),
  Heading2: wrap(Heading2),
  List: wrap(List),
  Quote: wrap(Quote),
  Link2: wrap(Link2),
  MoreVertical: wrap(MoreVertical),
  ScrollText: wrap(ScrollText),
  Flag: wrap(Flag),
  ArrowUp: wrap(ArrowUp),
  ChevronsUp: wrap(ChevronsUp),
  ChevronsDown: wrap(ChevronsDown),
};
